---
spring:
  profiles: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/lvxin_db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true
      username: root
      password: root
      # 最小连接数
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-init-sql: SELECT 1
      pool-name: im-api-hikari

---
spring:
  profiles: test
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      jdbc-url: jdbc:mysql://host.docker.internal:3306/lvxin_db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true
      username: root
      password: root
      # 最小连接数
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-init-sql: SELECT 1
      pool-name: im-api-hikari

---
spring:
  profiles: prod
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      jdbc-url: jdbc:mysql://172.22.0.2:3306/lvxin_db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true
      username: root
      password: root
      # 最小连接数
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-init-sql: SELECT 1
      pool-name: im-api-hikari